### ISSUE TITLE
How to rollback to a particular release?

### ISSUE THREAD

**Issue by AjeetK** [ansistrano/rollback#10]
Using Ansistrano rollback, we can rollback to the last release and with the subsequent rollback we can rollback to the n-1 release. But I want know how to rollback to any specific release directly?

**Comment by carlosbuenosvinos** [comment]
It's not supported for now, but we'll consider as a new feature. Thanks!

**Comment by AjeetK** [comment]
@carlosbuenosvinos Eager to see that feature :)

**Comment by cespedosa** [comment]
Hi Carlos.
When I launch the rollback playbook always restore the first release when should be the last.

Can you help me to understand the problem?

Thanks.

This is my playbooks content:

## **Deploy:**
- name: Deploy the application
  hosts: all
  remote_user: "{{ production_deploy_user }}"
  sudo: no
  
  vars:
   ansistrano_deploy_from: "../snowflake" # Base path to deploy from.
   ansistrano_deploy_to: "../snowflake3" # Base path to deploy to.
   ansistrano_version_dir: "releases" # Releases folder name
   ansistrano_current_dir: "current" # Softlink name. You should rarely changed it.
   ansistrano_remove_rolled_back: yes # You can change this setting in order to keep the rolled back release in the server for later inspection
   ansistrano_allow_anonymous_stats: yes
   ansistrano_keep_releases: 3
  
  roles:
  - carlosbuenosvinos.ansistrano-deploy

**Rollback:**

---
- name: Rollback the application
  hosts: all
  remote_user: "{{ production_deploy_user }}"
  sudo: no
  
  vars:
   ansistrano_deploy_to: "../snowflake3" # Base path to deploy to.
   ansistrano_version_dir: "releases" # Releases folder name
   ansistrano_current_dir: "current" # Softlink name. You should rarely changed it.
  
  roles:
  - carlosbuenosvinos.ansistrano-rollback

**Comment by ratbag98** [comment]
Hi @cespedosa . Not sure if this will fix your problem, but I found that the ls commands in [tasks/setup.yml](https://github.com/ansistrano/rollback/blob/master/tasks/setup.yml) were invalid. As written, the "-1t" appears after the release path, whereas it should be before, surely?

So each one needs switching around to look like:

``` yaml
shell: echo `ls -1t {{ ansistrano_releases_path.stdout }} | wc -l`
```

or similar. After making those changes, I found the role far more useful.

**Comment by ricardclau** [comment]
At least in Ubuntu you can put -1t before or after the release path... are you having an issue in some particular Linux distro? Rollback works as expected for many people

**Comment by ratbag98** [comment]
Hi @ricardclau . I'm on FreeBSD (same applies on Mac OS and probably other BSDs):

```
app1% touch test.txt
app1% ls test.txt -1t
ls: -1t: No such file or directory
test.txt
app1% ls -1t test.txt
test.txt
```

(Edit: removed man page reference]

**Comment by ricardclau** [comment]
Yeah, I suspected that, same happens in Mac as you said :)

Cool, will modify the ls calls, thanks!

**Comment by ricardclau** [comment]
Hi @ratbag98 and @cespedosa can you please test fix_bsd branch at https://github.com/ansistrano/rollback/pull/14 ?

**Comment by ratbag98** [comment]
@ricardclau - will test more fully later, but I can say that your code is identical to my revised code, so that's good enough for me. :) Thanks for the speedy responses.

**Comment by ricardclau** [comment]
Cool, will merge and tag as this is currently broken for such distros

Please @cespedosa provide more feedback when you get some time!
