### ISSUE TITLE
Rollback without deleting

### ISSUE THREAD

**Issue by robertmircea** [ansistrano/rollback#2]
Can I rollback to previous version without deleting the "bad" release directory? It is useful to keep the directory around in order to further analyse the reason which determined the rollback.

**Comment by ricardclau** [comment]
There is no such option at the moment.

We may consider adding it in the future but this may lead to potential problems with the ansistrano keep releases number so we would need to take this into account

A workaround (arguably dirty but I think it would work for your case) would be to re-deploy the previous version, so that the broken version stays there
