### ISSUE TITLE
I think...

### ISSUE THREAD

**Issue by free6k** [ansistrano/rollback#6]
I think that have need added setup-task.yml like in deploy, because in event before-symlink.yml i cant to get acces to variables ansistrano*. It shows in

What are you think about it?

**Comment by ricardclau** [comment]
Hi @free6k thanks for your suggestion

I think you are right, we could have a simple setup.yml file setting up the ansistrano variables (and also allow before and after setup steps). This way you would have them accessible in the before-symlink.yml task

Do you want to give it a go? Otherwise I will add this feature in the following days

Thank you!

**Comment by carlosbuenosvinos** [comment]
+1

Carlos Buenosvinos
@buenosvinos
